In [ ]:
#### 1. Import the numpy package under the name `np` (★☆☆)

In [9]:
import numpy as np 

In [10]:
#### 2. Create a null vector of size 10 (★☆☆)

In [27]:
a = np.zeros(10)
a
type(a)

numpy.ndarray

In [4]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
a[5] = 1

In [14]:
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [15]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [18]:
b = np.arange(10, 50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [19]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [21]:
c = np.arange(0, 9).reshape((3, 3))
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

`hint: np.nonzero`

In [34]:
d = [1,2,0,0,4,0]
d = np.array([d])

In [30]:
np.nonzero(d)

(array([0, 1, 4]),)

In [35]:
type(d)

numpy.ndarray

#### 7. Create a 3x3 identity matrix (★☆☆)

`hint: np.eye`

identity matrix of size n is the n × n square matrix with ones on the main diagonal and zeros elsewhere

In [45]:
identity_matrix = np.eye(3, 3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. Create a 3x3x3 array with random values (★☆☆)

`hint: np.random.random`

In [54]:
np.random.random((3, 3, 3))

array([[[0.48974957, 0.15231272, 0.49109412],
        [0.53700485, 0.21682048, 0.86616582],
        [0.15403656, 0.81749915, 0.96082095]],

       [[0.32157415, 0.41778298, 0.72342136],
        [0.47251607, 0.57946405, 0.73109756],
        [0.80999599, 0.15405477, 0.1105785 ]],

       [[0.23264801, 0.34699967, 0.23577092],
        [0.40968191, 0.47658938, 0.1384726 ],
        [0.61147988, 0.99889808, 0.81641131]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


`hint: min, max`

In [57]:
array_10_10 = np.random.random((10, 10))
array_10_10

array([[0.41736478, 0.22049784, 0.96075156, 0.11196667, 0.35018566,
        0.02274098, 0.11548097, 0.1507992 , 0.35968023, 0.70485186],
       [0.74316852, 0.43290199, 0.19672062, 0.45681377, 0.6077982 ,
        0.18386369, 0.45173837, 0.46074071, 0.04342216, 0.76555458],
       [0.88354867, 0.1585752 , 0.40069706, 0.44572704, 0.99827817,
        0.52340546, 0.16867073, 0.94050469, 0.77337581, 0.8203536 ],
       [0.6078246 , 0.77967864, 0.37577922, 0.12445034, 0.27644661,
        0.53685466, 0.24447298, 0.05941911, 0.41566994, 0.9459693 ],
       [0.24916536, 0.94277213, 0.80358645, 0.08951136, 0.44416166,
        0.00300191, 0.61671159, 0.40642438, 0.43571566, 0.42761594],
       [0.45798697, 0.13012686, 0.06496354, 0.82193123, 0.93302044,
        0.06519622, 0.58310826, 0.21970495, 0.54923214, 0.36806662],
       [0.82778267, 0.64248706, 0.48107526, 0.86708167, 0.61782442,
        0.94886028, 0.95803778, 0.72342184, 0.76756776, 0.93316699],
       [0.09342993, 0.30890323, 0.6857353

In [61]:
np.min(array_10_10)

0.0028677949606338293

In [62]:
np.max(array_10_10)

0.9982781703320228

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

42

`hint: mean`

In [65]:
vector_30 = np.random.random((30))
vector_30

array([0.63831072, 0.22302161, 0.93904276, 0.25397515, 0.65562354,
       0.53216918, 0.99329761, 0.19905339, 0.29192601, 0.52014638,
       0.84281171, 0.29445341, 0.84415871, 0.19222415, 0.97457066,
       0.27544461, 0.63699719, 0.56795287, 0.11111014, 0.24999324,
       0.64743209, 0.7646168 , 0.30357971, 0.60517101, 0.66370472,
       0.14111198, 0.19632488, 0.41486189, 0.20728787, 0.50846906])

In [67]:
mean_vec = np.mean(vector_30)

In [69]:
round(mean_vec, 2)

0.49

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

`hint: np.diag`

In [71]:
array_5_5 = np.random.random((5, 5))

In [72]:
array_5_5

array([[0.04168008, 0.71628017, 0.40823548, 0.18987748, 0.6093372 ],
       [0.37237132, 0.17098896, 0.66681943, 0.73388266, 0.05589899],
       [0.51618419, 0.52855168, 0.80798327, 0.29806916, 0.21948844],
       [0.42145488, 0.5681216 , 0.58546002, 0.99551072, 0.27710756],
       [0.34578227, 0.42137885, 0.59229822, 0.79466177, 0.65055358]])

In [101]:
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 12. Normalize a 5x5 random matrix (★☆☆)

`hint: (x - mean)/std`

In [149]:
normal_array = np.random.random((5, 5))
normal_array

array([[0.09922209, 0.11358971, 0.32476618, 0.53102657, 0.7751737 ],
       [0.99392459, 0.32474734, 0.29034924, 0.64032344, 0.62262937],
       [0.01921934, 0.913562  , 0.09060549, 0.82960358, 0.37537756],
       [0.18284544, 0.54223921, 0.32396879, 0.34347433, 0.69115507],
       [0.03027931, 0.97536008, 0.95617371, 0.43726088, 0.14875275]])

In [150]:
array_max = np.max(normal_array)

In [151]:
array_max

0.9939245900781628

In [152]:
array_min = np.min(normal_array)

In [153]:
array_min

0.019219335644724445

In [141]:
difference_max_min = array_max - array_min

In [142]:
difference_max_min

0.9343393142893639

In [143]:
mean = np.mean(normal_array)

In [144]:
std = np.std(normal_array)

In [156]:
## doesn't work ?
x = (normal_array - mean) / std

In [157]:
x

array([[-1.71103169, -1.66533829, -0.99373297, -0.33776221,  0.43869984],
       [ 1.13439416, -0.99379287, -1.10318928,  0.00983503, -0.04643749],
       [-1.96546478,  0.8788167 , -1.73843511,  0.61180341, -0.83277338],
       [-1.44508403, -0.30210262, -0.9962689 , -0.93423534,  0.17149507],
       [-1.93029069,  1.07535338,  1.01433488, -0.63596562, -1.55350915]])

In [154]:
y = ((normal_array - array_min) / (array_max - array_min))

In [155]:
y

array([[0.08207892, 0.0968194 , 0.31347614, 0.52508924, 0.77557226],
       [1.        , 0.31345682, 0.27816604, 0.63722248, 0.61906923],
       [0.        , 0.9175519 , 0.07323871, 0.83141467, 0.36540095],
       [0.1678724 , 0.53659285, 0.31265806, 0.33266979, 0.68937325],
       [0.011347  , 0.98095372, 0.96126944, 0.42889021, 0.13289496]])

In [ ]:
#### 13. How does one find common values between two arrays? (★☆☆)


`hint: np.intersect1d`


In [161]:
array_1 = [1, 3, 5, 7]
array_2 = [1, 2, 4, 10]
np.intersect1d(array_1, array_2)

array([1])


#### 14. Create a random vector of size 10 and sort it (★★☆)


`hint: sort`

In [165]:
ran_vec = sort(np.array((10)))

NameError: name 'sort' is not defined

In [177]:
ran_vec = np.random.random(10)
ran_vec

array([0.48346616, 0.13219412, 0.13916297, 0.98969379, 0.27764825,
       0.65656516, 0.24122685, 0.6767931 , 0.73150717, 0.99729757])

In [179]:
np.sort(ran_vec)

array([0.13219412, 0.13916297, 0.24122685, 0.27764825, 0.48346616,
       0.65656516, 0.6767931 , 0.73150717, 0.98969379, 0.99729757])

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

`hint: argmax`

In [199]:
ran_vec_2 = np.random.random(10)

In [200]:
ran_vec_2

array([0.36271361, 0.63758535, 0.97231951, 0.33998498, 0.93906416,
       0.12099434, 0.34798113, 0.27567179, 0.32505706, 0.18123891])

In [201]:
max_value_vec_2 = np.argmax(ran_vec_2)

In [202]:
max_value_vec_2

2

In [203]:
ran_vec_2[6] = 0

In [204]:
ran_vec_2

array([0.36271361, 0.63758535, 0.97231951, 0.33998498, 0.93906416,
       0.12099434, 0.        , 0.27567179, 0.32505706, 0.18123891])

#### 16. Subtract the mean of each row of a matrix (★★☆)

`hint: mean(axis=,keepdims=)`

In [211]:
matrix_16 = np.random.random((3, 3))

In [212]:
matrix_16

array([[0.44801977, 0.42158083, 0.26206512],
       [0.74004791, 0.22574569, 0.39494816],
       [0.14856053, 0.28409531, 0.56337694]])

In [224]:
mean_by_row = np.mean(matrix_16, axis=1, keepdims=True)
mean_by_row

array([[0.37722191],
       [0.45358059],
       [0.33201093]])

In [223]:
matrix_16 - mean_by_row

array([[ 0.07079786, -0.03199976, -0.06994581],
       [ 0.36282601, -0.2278349 ,  0.06293723],
       [-0.22866137, -0.16948527,  0.23136601]])

17. How can one get the n largest values of an array? (★★★)

In [234]:
array_17 = np.arange(10000)
np.random.shuffle(array_17) 

In [233]:
array_17

array([6964, 3840, 2335, ..., 1672, 5905, 2772])

In [244]:
sorted_array = np.argsort(array_17)[-5:]
sorted_array

array([5738, 9555, 3226, 6759, 2970])

In [245]:
array_17[sorted_array]

array([9995, 9996, 9997, 9998, 9999])

In [246]:
## np.argpartition

In [ ]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 

`hint: np.where`

In [274]:
array_18 = np.random.randint(0, 10, (5, 3))
array_18

array([[7, 3, 1],
       [9, 6, 1],
       [6, 2, 9],
       [0, 0, 9],
       [0, 0, 5]])

In [277]:
list_larger = np.where(array_18 < 4, array_18, array_18**2)

In [278]:
list_larger

array([[49,  3,  1],
       [81, 36,  1],
       [36,  2, 81],
       [ 0,  0, 81],
       [ 0,  0, 25]])